### ISSUE TITLE
Animation And Transition

### ISSUE THREAD

**Issue by DhuruvSingh** [JoffreyNK/portfolio-desktop#6]
### Minor Changes Required

- [ ] [OPTIONAL] :

1. Please try to remove the animation in the hamburger button in the mobile version.

- It's not a good practice to animate the dropdown button.

2.  Please change the length of the logo rotation.

- It's not looking good when your logo keeps rotation. the logo is something people want to recognize if your logo keeps rotating how they can see what's inside the logo.

**Comment by pirc25** [comment]
- [ ] [Optional]:

It's a good job, however, you can give time to do the animation and then stop. because those animations can be a distraction for the readers.

**Comment by joffreynk** [comment]
the animations was solved as discussed
